kind: pipeline
type: exec
name: push_event
platform:
  os: linux
  arch: amd64

steps:
- name: unit test
  commands:
  - source .bashrc
  - cd /data2/kevin7552/financial__management/fastapi/test
  - pytest test_mail.py