kind: pipeline
type: docker
name: push_event
steps:
  - name: unit test
    image: "finance_management:v1"
    commands:
      - cd /home/financial__management/fastapi/test
      - pytest test_mail.py
    volumes:
      - name: source_code
        path: /home/financial__management
volumns:
  - name: source_code
    host:
      path: /data2/kevin7552/financial__management