APIKey: c2b24a2f-3402-46a0-8d69-ece52f28bb09
DomainName: pro-api.coinmarketcap.com
uri: /v1/cryptocurrency/quotes/latest
symbols: 
    - ETH
    - FTT
    - MOVR
    - DOT
    - META
    - BTC
    - XY
    - SUPER